### ISSUE TITLE
How should I implement CRUD in the movie app?

### ISSUE THREAD

**Issue by amite** [CodeGurukul/ror-sample-project#3]
If I am working with a web api to populate the api, that takes care of creating movie records - that means attendees don't get to see html forms and typical CRUD web interfaces that they would expect to see.

Does this make sense in that case?

**Comment by amite** [comment]
Made a basic crud app that will live in a separate branch only for demo purposes:

![screen shot 2015-02-16 at 7 00 37 pm](https://cloud.githubusercontent.com/assets/1308947/6212715/4741032e-b60e-11e4-8399-87cbb7ee3d65.png)

![screen shot 2015-02-16 at 7 00 47 pm](https://cloud.githubusercontent.com/assets/1308947/6212717/49d9df66-b60e-11e4-9084-1cb1521ec7d4.png)

![screen shot 2015-02-16 at 7 00 57 pm](https://cloud.githubusercontent.com/assets/1308947/6212719/4aac1fa8-b60e-11e4-9806-c5174dcc3ade.png)

**Comment by sobingt** [comment]
@amite so the sample app and crud will be in separate branches?

Will we explain both to the students?

**Comment by amite** [comment]
Yes - this is why we will keep it in a separate branch and then start again manually

**Comment by amite** [comment]
@sobingt I accidentally cloned it in your master branch - I shoulda kept it in a separate branch like on my repo

**Comment by sobingt** [comment]
cool

_with regards_

_Sobin George Thomas_

_www.sobingt.com_ http://www.sobingt.com/its _So Begins
Innovative Geek Talks   *_sobingt.com http://sobingt.com/*
*Code Artist.... :)http://www.facebook.com/sobingt
http://www.facebook.com/sobingthttp://www.bitbrothers.in
http://www.bitbrothers.in *8097415085 022-28945268(India) , c/o
056-6854097(Abu Dhabi)
